# syntax = docker/dockerfile:1

ARG RUBY_VERSION=3.4.2
FROM ruby:$RUBY_VERSION-slim-bookworm

WORKDIR /rails

RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
    build-essential \
    default-mysql-client \
    libmariadb-dev-compat \
    pkg-config \
    curl \
    git \
    libyaml-dev \
  && rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN --mount=type=cache,target=/usr/local/bundle/cache \
    bundle install

COPY . .

EXPOSE 3000

CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"]
