development:
  adapter: redis
  url: redis://<%= ENV.fetch("REDIS_HOST", "localhost") %>:<%= ENV.fetch("REDIS_PORT", 6379) %>/<%= ENV.fetch("REDIS_DB", 0) %>

test:
  adapter: test

staging:
  adapter: redis
  url: redis://<%= ENV.fetch("REDIS_HOST", "localhost") %>:<%= ENV.fetch("REDIS_PORT", 6379) %>/<%= ENV.fetch("REDIS_DB", 0) %>

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/0") %>
